### ISSUE TITLE
missing dependencies on linux

### ISSUE THREAD

**Issue by EastEriq** [illuminated-g/lv-http-server#13]
AFAIU (LV2021-64 on Ubuntu), as it stands, several VI are broken because 
"Escape HTTP URL.vi" and "Unescape HTTP URL.vi" are missing. I had these lying around on disk from another project, likely former grabs from the windows installation of <vi.lib>/wsapi/VIs.
Moreover:

- mime.types is missing
- Say Hi Msg Callback.vi is expected at a non exisiting Z/IlluminatedG/ path

**Comment by negentropicdev** [comment]
I'll pull that functionality into the HTTP library and remove the dependency on web services functionality.

**Comment by negentropicdev** [comment]
The WebSocket upgrade example should be fixed now too.

**Comment by EastEriq** [comment]
Perfect, that seems to have fixed all the missing deps I ran into yesterday. Thanks for having taken care so quickly and even push the updates already to vipm.

**Comment by negentropicdev** [comment]
JKI made updating existing packages on VIPM very quick so it makes it possible to respond that quickly. Plus it helps that the issues were very small :)

Cheers
